INSERT INTO game (code) VALUES
    ('TIME_STRANGER');

INSERT INTO attribute (code) VALUES
                                 ('VACCINE'),
                                 ('DATA'),
                                 ('VIRUS'),
                                 ('FREE'),
                                 ('VARIABLE'),
                                 ('UNKNOWN'),
                                 ('NO_DATA');

INSERT INTO generation (code, rank) VALUES
                                        ('IN_TRAINING_I',  1),
                                        ('IN_TRAINING_II', 2),
                                        ('ROOKIE',         3),
                                        ('CHAMPION',       4),
                                        ('ULTIMATE',       5),
                                        ('MEGA',           6),
                                        ('MEGA_PLUS',      7),
                                        ('ARMOR',          8),
                                        ('HYBRID',         9);

INSERT INTO digimon_type (code) VALUES
                                    ('ABNORMAL'),
                                    ('ALIEN'),
                                    ('AMPHIBIAN'),
                                    ('ANCIENT_BEAST'),
                                    ('ANCIENT_BIRD'),
                                    ('ANCIENT_CRUSTACEAN'),
                                    ('ANCIENT_DRAGON'),
                                    ('ANCIENT_DRAGON_MAN'),
                                    ('ANCIENT_FISH'),
                                    ('ANCIENT_HOLY_KNIGHT'),
                                    ('ANCIENT_MUTANT'),
                                    ('ANDROID'),
                                    ('ANGEL'),
                                    ('AQUATIC'),
                                    ('AQUATIC_BEAST_MAN'),
                                    ('ARMORED_DRAGON'),
                                    ('BABY_BIRD'),
                                    ('BEAST'),
                                    ('BEAST_DRAGON'),
                                    ('BEAST_KNIGHT'),
                                    ('BEAST_MAN'),
                                    ('BIRD'),
                                    ('BIRD_MAN'),
                                    ('BULB'),
                                    ('CARNIVOROUS_VEGETATION'),
                                    ('CERATOPSIAN'),
                                    ('CHERUB'),
                                    ('COMPOSITE'),
                                    ('CRUSTACEAN'),
                                    ('DARK_ANGEL'),
                                    ('DARK_BEAST'),
                                    ('DARK_DRAGON'),
                                    ('DARK_KNIGHT'),
                                    ('DEITY'),
                                    ('DEMON'),
                                    ('DEMON_GOD'),
                                    ('DINOSAUR'),
                                    ('DRAGON'),
                                    ('DRAGON_MAN'),
                                    ('DRAGON_WARRIOR'),
                                    ('EARTH_DRAGON'),
                                    ('EVIL_DRAGON'),
                                    ('EVIL_KING'),
                                    ('FIRE'),
                                    ('GALAXY'),
                                    ('GHOST'),
                                    ('GIANT_BIRD'),
                                    ('GREAT_ANGEL'),
                                    ('HIGH_ANGEL'),
                                    ('HOLY_BEAST'),
                                    ('HOLY_BIRD'),
                                    ('HOLY_DRAGON'),
                                    ('HOLY_KNIGHT'),
                                    ('HOLY_SWORD'),
                                    ('ICE_SNOW'),
                                    ('INSECTOID'),
                                    ('INVADER'),
                                    ('LARVA'),
                                    ('LESSER'),
                                    ('LITTLE_DEVIL'),
                                    ('MACHINE'),
                                    ('MACHINE_DRAGON'),
                                    ('MAGIC_WARRIOR'),
                                    ('MAMMAL'),
                                    ('MINERAL'),
                                    ('MINI_DRAGON'),
                                    ('MOLLUSK'),
                                    ('MUTANT'),
                                    ('MYSTERIOUS_BEAST'),
                                    ('MYSTERIOUS_BIRD'),
                                    ('MYTHICAL_BEAST'),
                                    ('MYTHICAL_DRAGON'),
                                    ('NO_DATA'),
                                    ('ORE'),
                                    ('PERFECT'),
                                    ('PIXIE'),
                                    ('PLESIOSAUR'),
                                    ('PUPPET'),
                                    ('RARE_ANIMAL'),
                                    ('REPTILE'),
                                    ('SEA_ANIMAL'),
                                    ('SEA_BEAST'),
                                    ('SERAPH'),
                                    ('SHINING_DRAGON'),
                                    ('SKY_DRAGON'),
                                    ('SLIME'),
                                    ('SUPER_ANGEL'),
                                    ('UNDEAD'),
                                    ('UNIDENTIFIED'),
                                    ('UNIQUE'),
                                    ('VEGETATION'),
                                    ('VIRTUE'),
                                    ('WARRIOR'),
                                    ('WEAPON'),
                                    ('WIZARD');