spring:
  application:
    name: digimon-api

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/digimon
    username: digimon
    password: digimon
    driverClassName: org.postgresql.Driver
